### ISSUE TITLE
RuntimeError occurs while sending basic commands

### ISSUE THREAD

**Issue by intcreator** [krs013/mse430#1]
I cannot execute even simple commands from the command line (connecting to the server with `telnet`).  Here is an example output:

```
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
speed 3 3
speed 3 3
RuntimeError occurred while handling "speed 3 3": read() called while another coroutine is already waiting for incoming data
```

The first command does not produce an error but also does not cause the robot to move.  The second command causes the error to display.

I'm running this using Python 3 on macOS Sierra.

Is this something I can fix?

**Comment by intcreator** [comment]
Pushing the reset button on the MSP-430 appeared to fix this problem.

**Comment by krs013** [comment]
The two underlying issues are that 1) there is no underlying support for backed up, concurrent, or timed out messages, and 2) for reasons unknown, the firmware stalls when the robot turns on, and has to be reset with the button. Sadly, I don’t have a ready solution for either of these issues.
